# Generated by Django 6.0.7 on 2026-07-27 02:51

import detection.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0002_aimodel_classes_aimodel_description_aimodel_imgsz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(help_text='Original uploaded image or video.', upload_to=detection.models.original_upload_path)),
                ('result_file', models.FileField(blank=True, help_text='Annotated output file (image or video).', null=True, upload_to=detection.models.result_upload_path)),
                ('detection_mode', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic'), ('webcam', 'Webcam')], default='manual', max_length=20)),
                ('confidence_used', models.FloatField(default=0.25, help_text='Confidence threshold applied (0.0–1.0).')),
                ('iou_used', models.FloatField(default=0.45, help_text='IoU threshold applied (0.0–1.0).')),
                ('detections', models.JSONField(blank=True, default=list, help_text='List of detected objects: [{bbox, confidence, class_id, class_name}, ...]')),
                ('object_count', models.PositiveIntegerField(default=0, help_text='Total number of objects detected.')),
                ('inference_time_ms', models.FloatField(blank=True, help_text='Model inference time in milliseconds.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_records', to='ai.aimodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detection Record',
                'verbose_name_plural': 'Detection Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='detection_d_user_id_ee16ac_idx'), models.Index(fields=['ai_model'], name='detection_d_ai_mode_cf2341_idx'), models.Index(fields=['detection_mode'], name='detection_d_detecti_6e5d0c_idx')],
            },
        ),
    ]
