# Generated by Django 6.0.7 on 2026-07-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionrecord',
            name='detection_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic'), ('video', 'Video'), ('webcam', 'Webcam')], default='manual', max_length=20),
        ),
    ]
