# Generated by Django 6.0.7 on 2026-07-21 19:24

import ai.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable model name, e.g. 'Helmet Detector'.", max_length=100)),
                ('category', models.CharField(choices=[('helmet', 'Helmet'), ('vehicle', 'Vehicle'), ('bike', 'Bike'), ('custom', 'Custom')], help_text='Detection category this model is responsible for.', max_length=20)),
                ('version', models.CharField(help_text="Free-form version string, e.g. '1.0', '2.0.1', '2026-07-22'.", max_length=32)),
                ('weight_file', models.FileField(help_text='The .pt / .onnx / .engine weight file. Stored under media/models/<category>/.', upload_to=ai.models.model_upload_path)),
                ('weight_format', models.CharField(choices=[('pt', 'PyTorch (.pt)'), ('onnx', 'ONNX (.onnx)'), ('engine', 'TensorRT (.engine)')], default='pt', max_length=10)),
                ('default_confidence', models.FloatField(default=0.25, help_text='Default confidence threshold (0.0 - 1.0).')),
                ('default_iou', models.FloatField(default=0.45, help_text='Default IoU threshold for NMS (0.0 - 1.0).')),
                ('accuracy', models.FloatField(blank=True, help_text='Optional reported accuracy (e.g. mAP) at upload time. 0.0 - 1.0.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive models are soft-deleted — they are skipped by the loader.')),
                ('is_default', models.BooleanField(default=False, help_text='If true, this model is returned by load_default(category=...) for its category. Only one default per category is allowed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', '-is_default', '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='ai_aimodel_categor_4eeed5_idx'), models.Index(fields=['is_default'], name='ai_aimodel_is_defa_bd0725_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'version', 'category'), name='unique_model_name_version_category')],
            },
        ),
    ]
