# Generated by Django 6.0.7 on 2026-07-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='classes',
            field=models.JSONField(blank=True, default=list, help_text="List of class names this model predicts, e.g. ['helmet', 'no_helmet']."),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='description',
            field=models.CharField(blank=True, help_text='Optional free-text description of the model.', max_length=500),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='imgsz',
            field=models.PositiveIntegerField(default=640, help_text='Inference image size (e.g. 640).'),
        ),
    ]
